const DEFAULT_TOOL_NAMES = [
  "activePullRequest",
  "applyPatch",
  "askQuestions",
  "azureActivityLog",
  "Build_CMakeTools",
  "changes",
  "clickElement",
  "codebase",
  "configurePythonEnvironment",
  "containerToolsConfig",
  "cpp",
  "create_pull_request",
  "createAndRunTask",
  "createDirectory",
  "createFile",
  "createJupyterNotebook",
  "doSearch",
  "dragElement",
  "editFiles",
  "editNotebook",
  "executionSubagent",
  "exploreSubagent",
  "extensions",
  "fetch",
  "fileSearch",
  "findDotNetPath",
  "findTestFiles",
  "GetDiagnostics_CMakeTools",
  "getDotNetSettingsInfo",
  "getNotebookSummary",
  "getPythonEnvironmentInfo",
  "getPythonExecutableCommand",
  "GetSymbolCallHierarchy_CppTools",
  "GetSymbolInfo_CppTools",
  "GetSymbolReferences_CppTools",
  "getTaskOutput",
  "getTerminalOutput",
  "githubRepo",
  "githubTextSearch",
  "handleDialog",
  "hoverElement",
  "insertEdit",
  "installDotNetSdk",
  "installExtension",
  "installPythonPackage",
  "issue_fetch",
  "killTerminal",
  "labels_fetch",
  "ListBuildTargets_CMakeTools",
  "listDirectory",
  "listDotNetVersions",
  "listInstalledDotNetVersions",
  "ListTests_CMakeTools",
  "memory",
  "mssql_change_database",
  "mssql_connect",
  "mssql_dab",
  "mssql_disconnect",
  "mssql_get_connection_details",
  "mssql_list_databases",
  "mssql_list_functions",
  "mssql_list_schemas",
  "mssql_list_servers",
  "mssql_list_tables",
  "mssql_list_views",
  "mssql_run_query",
  "mssql_schema_designer",
  "multiReplaceString",
  "navigatePage",
  "newWorkspace",
  "notification_fetch",
  "openBrowserPage",
  "openPullRequest",
  "prisma-migrate-dev",
  "prisma-migrate-reset",
  "prisma-migrate-status",
  "prisma-platform-login",
  "prisma-postgres-create-database",
  "prisma-studio",
  "problems",
  "pullRequestStatusChecks",
  "pylanceDocString",
  "pylanceDocuments",
  "pylanceFileSyntaxErrors",
  "pylanceImports",
  "pylanceInstalledTopLevelModules",
  "pylanceInvokeRefactoring",
  "pylancePythonEnvironments",
  "pylanceRunCodeSnippet",
  "pylanceSettings",
  "pylanceSyntaxErrors",
  "pylanceUpdatePythonEnvironment",
  "pylanceWorkspaceRoots",
  "pylanceWorkspaceUserFiles",
  "readFile",
  "readNotebookCellOutput",
  "readPage",
  "recommendedDotNetSdkVersion",
  "rename",
  "renderMermaidDiagram",
  "replaceString",
  "resolveMemoryFileUri",
  "resolveReviewThread",
  "reviewPlan",
  "runCommand",
  "RunCtest_CMakeTools",
  "runInTerminal",
  "runNotebookCell",
  "runPlaywrightCode",
  "runSubagent",
  "runTask",
  "runTests",
  "screenshotPage",
  "searchSubagent",
  "sendToTerminal",
  "sessionStoreSql",
  "skill",
  "switchAgent",
  "symbols",
  "terminalLastCommand",
  "terminalSelection",
  "testFailure",
  "textSearch",
  "todo",
  "toolSearch",
  "typeInPage",
  "uninstallSystemDotNetSdk",
  "uninstallVSCodeDotNetRuntime",
  "usages",
  "viewImage",
  "vscodeAPI",
];

/** Builds the per-tool eligibleForAutoApproval map with every tool set to false. */
export const buildToolEligibilityDenyAll = (
  extraToolNames: string[] = []
): Record<string, boolean> => {
  const names = new Set([...DEFAULT_TOOL_NAMES, ...extraToolNames]);
  const out: Record<string, boolean> = {};
  for (const name of names) {
    out[name] = false;
  }
  return out;
};

export const HITL_SETTING_KEYS = {
  globalAutoApprove: "chat.tools.global.autoApprove",
  terminalEnableAutoApprove: "chat.tools.terminal.enableAutoApprove",
  terminalAutoApprove: "chat.tools.terminal.autoApprove",
  eligibleForAutoApproval: "chat.tools.eligibleForAutoApproval",
} as const;
